# Generated by Django 3.0.7 on 2020-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
